import Head from 'next/head'
import { Inter } from 'next/font/google'
import Door from '../components/Door'
import DoorModel from '../model/door'
const inter = Inter({ subsets: ['latin'] })
import { useState } from 'react'

export default function Home() {

  const [p1, setP1 ] = useState(new DoorModel(1))

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Door door={p1} />
      </main>
    </>
  )
}
